services:
  - type: web
    name: breast-cancer-prediction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2